### ISSUE TITLE
DOVECOT_ABI_VERSION

### ISSUE THREAD

**Issue by JulienCharge** [ascendantcom/fts-elasticsearch#1]
Hello,
I want to install your plugins with Dovecot 2.1.17 .
When compiling I get the following error.

Do you have an idea of ​​my problem, I have forgotten to install a component?

Thank you for your time

thank you

 error: 'DOVECOT_ABI_VERSION' undeclared here (not in a function)
make[1]: **\* [fts-elasticsearch-plugin.lo] Erreur 1
make[1]: quittant le répertoire « /etc/dovecot/fts-elasticsearch/src »
make: **\* [install-recursive] Erreur 1

**Comment by atkinsj** [comment]
Hi,

Looks like we've found the minimum Dovecot version! DOVECOT_ABI_VERSION was
introduced in Dovecot 2.2+.

The 2.1.17 version you're running is old--are you able to upgrade? There might be some work I can do to support a version that old by switching from DOVECOT_ABI_VERSION to a macro that also supports DOVECOT_VERSION (the old parameter) but I don't know how versions that old will go with everything else.

Cheers,
Josh

**Comment by JulienCharge** [comment]
thank you ,

I have a small quesrion is it possible in a simple way to add fields in the json . This field specifies the name of dovecot directory (eg .INBOX.archives ) ?

Because we would like to search ElasticSearch based on subdirectory of the box.

According to you is that this manipulation is possible?

Thank you for your answers and your time.


Best Regards,
Julian
