### ISSUE TITLE
Compiling on CentOS 7 (RHEL7)

### ISSUE THREAD

**Issue by adundovi** [ascendantcom/fts-elasticsearch#11]
What is the minimum required version of C++ standard?

I've tried to compile it with `gcc version 4.8.5 20150623 (Red Hat 7.5) (GCC)` and it is throwing: 
```
fts-backend-elasticsearch.c:670:41: warning: its scope is only this definition or declaration, which is probably not what you want [enabled by default]
fts-backend-elasticsearch.c:669:56: error: parameter 4 ('flags') has incomplete type
                                  enum fts_lookup_flags flags,
                                                        ^
fts-backend-elasticsearch.c: In function 'fts_backend_elasticsearch_lookup':
fts-backend-elasticsearch.c:675:30: error: 'FTS_LOOKUP_FLAG_AND_ARGS' undeclared (first use in this function)
     bool and_args = (flags & FTS_LOOKUP_FLAG_AND_ARGS) != 0;
                              ^
fts-backend-elasticsearch.c:675:30: note: each undeclared identifier is reported only once for each function it appears in
fts-backend-elasticsearch.c:742:48: error: 'FTS_LOOKUP_FLAG_NO_AUTO_FUZZY' undeclared (first use in this function)
     ARRAY_TYPE(seq_range) *uids_arr = (flags & FTS_LOOKUP_FLAG_NO_AUTO_FUZZY) == 0 ?
```

If C+11 or newer is required could you please add it to README.md?

**Comment by ghost** [comment]
same on ubuntu 14.04

**Comment by robisonjoel** [comment]
same WRT ubuntu 14.04
```
fts-backend-elasticsearch.c: In function 'fts_backend_elasticsearch_rescan':
fts-backend-elasticsearch.c:570:5: warning: implicit declaration of function 'fts_backend_reset_last_uids' [-Wimplicit-function-declaration]
     return fts_backend_reset_last_uids(backend);
     ^
fts-backend-elasticsearch.c: At top level:
fts-backend-elasticsearch.c:670:41: warning: 'enum fts_lookup_flags' declared inside parameter list [enabled by default]
                                  struct fts_result *result)
                                         ^
fts-backend-elasticsearch.c:670:41: warning: its scope is only this definition or declaration, which is probably not what you want [enabled by default]
fts-backend-elasticsearch.c:669:56: error: parameter 4 ('flags') has incomplete type
                                  enum fts_lookup_flags flags,
                                                        ^
fts-backend-elasticsearch.c: In function 'fts_backend_elasticsearch_lookup':
fts-backend-elasticsearch.c:675:30: error: 'FTS_LOOKUP_FLAG_AND_ARGS' undeclared (first use in this function)
     bool and_args = (flags & FTS_LOOKUP_FLAG_AND_ARGS) != 0;
                              ^
fts-backend-elasticsearch.c:675:30: note: each undeclared identifier is reported only once for each function it appears in
fts-backend-elasticsearch.c:742:48: error: 'FTS_LOOKUP_FLAG_NO_AUTO_FUZZY' undeclared (first use in this function)
     ARRAY_TYPE(seq_range) *uids_arr = (flags & FTS_LOOKUP_FLAG_NO_AUTO_FUZZY) == 0 ?
                                                ^
fts-backend-elasticsearch.c:669:56: warning: unused parameter 'flags' [-Wunused-parameter]
                                  enum fts_lookup_flags flags,
                                                        ^
fts-backend-elasticsearch.c: At top level:
fts-backend-elasticsearch.c:779:9: warning: initialization from incompatible pointer type [enabled by default]
         fts_backend_elasticsearch_lookup,
         ^
fts-backend-elasticsearch.c:779:9: warning: (near initialization for 'fts_backend_elasticsearch.v.lookup') [enabled by default]
fts-backend-elasticsearch.c:781:5: warning: missing initializer for field 'lookup_done' of 'struct fts_backend_vfuncs' [-Wmissing-field-initializers]
     }
     ^
In file included from fts-elasticsearch-plugin.h:5:0,
                 from fts-backend-elasticsearch.c:17:
/root/downloads/dovecot/dovecot-2.2.9/src/plugins/fts/fts-api-private.h:51:9: note: 'lookup_done' declared here
  void (*lookup_done)(struct fts_backend *backend);
         ^
make[2]: *** [fts-backend-elasticsearch.lo] Error 1
make[2]: Leaving directory `/root/downloads/dovecot/fts-elasticsearch/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/downloads/dovecot/fts-elasticsearch'
make: *** [all] Error 2
```

**Comment by grharry** [comment]
Compile error on debian jessie,
fts-backend-elasticsearch.c:781:5: warning: missing initializer for field 'lookup_done' of 'struct fts_backend_vfuncs' [-Wmissing-field-initializers]
     }
     ^
In file included from fts-elasticsearch-plugin.h:5:0,
                 from fts-backend-elasticsearch.c:17:
/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/plugins/fts/fts-api-private.h:52:9: note: 'lookup_done' declared here
  void (*lookup_done)(struct fts_backend *backend);
         ^
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/plugins/fts -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27 -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-dict -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-dns -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-http -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-mail -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-imap -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-fs -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-charset -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-auth -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-master -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-ssl-iostream -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-compression -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-settings -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-test -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-sasl -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-stats -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-dcrypt -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-program-client -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-index -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-storage -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-storage/list -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-storage/index -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-storage/index/raw -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-imap-storage -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/plugins/quota -std=gnu99 -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wall -W -Wmissing-prototypes -Wmissing-declarations -Wpointer-arith -Wchar-subscripts -Wformat=2 -Wbad-function-cast -fno-builtin-strftime -Wstrict-aliasing=2 -I.. -MT fts-backend-elasticsearch.lo -MD -MP -MF .deps/fts-backend-elasticsearch.Tpo -c fts-backend-elasticsearch.c -fPIE -o fts-backend-elasticsearch.o >/dev/null 2>&1
mv -f .deps/fts-backend-elasticsearch.Tpo .deps/fts-backend-elasticsearch.Plo
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..    -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/plugins/fts -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27 -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-dict -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-dns -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-http -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-mail -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-imap -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-fs -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-charset -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-auth -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-master -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-ssl-iostream -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-compression -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-settings -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-test -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-sasl -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-stats -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-dcrypt -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-program-client -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-index -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-storage -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-storage/list -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-storage/index -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-storage/index/raw -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-imap-storage -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/plugins/quota  -std=gnu99 -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wall -W -Wmissing-prototypes -Wmissing-declarations -Wpointer-arith -Wchar-subscripts -Wformat=2 -Wbad-function-cast -fno-builtin-strftime -Wstrict-aliasing=2  -I.. -MT elasticsearch-conn.lo -MD -MP -MF .deps/elasticsearch-conn.Tpo -c -o elasticsearch-conn.lo elasticsearch-conn.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/plugins/fts -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27 -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-dict -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-dns -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-http -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-mail -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-imap -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-fs -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-charset -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-auth -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-master -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-ssl-iostream -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-compression -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-settings -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-test -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-sasl -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-stats -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-dcrypt -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-program-client -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-index -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-storage -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-storage/list -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-storage/index -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-storage/index/raw -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/lib-imap-storage -I/root/dovecot-elastic/dovecot-2.2.27/dovecot-2.2.27/src/plugins/quota -std=gnu99 -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wall -W -Wmissing-prototypes -Wmissing-declarations -Wpointer-arith -Wchar-subscripts -Wformat=2 -Wbad-function-cast -fno-builtin-strftime -Wstrict-aliasing=2 -I.. -MT elasticsearch-conn.lo -MD -MP -MF .deps/elasticsearch-conn.Tpo -c elasticsearch-conn.c  -fPIC -DPIC -o .libs/elasticsearch-conn.o
elasticsearch-conn.c: In function 'elasticsearch_connection_init':
elasticsearch-conn.c:87:40: error: 'struct http_url' has no member named 'host'
     conn->http_host = i_strdup(http_url->host.name);
                                        ^
elasticsearch-conn.c: In function 'json_parse_array':
elasticsearch-conn.c:193:9: warning: 'json_object_object_get' is deprecated (declared at /usr/include/json-c/json_object.h:271) [-Wdeprecated-declarations]
         jarray = json_object_object_get(jobj, key);
         ^
elasticsearch-conn.c: In function 'json_parse':
elasticsearch-conn.c:346:13: warning: 'json_object_object_get' is deprecated (declared at /usr/include/json-c/json_object.h:271) [-Wdeprecated-declarations]
             temp = json_object_object_get(jobj, key);
             ^
Makefile:457: recipe for target 'elasticsearch-conn.lo' failed
make[2]: *** [elasticsearch-conn.lo] Error 1
make[2]: Leaving directory '/root/dovecot-elastic/fts-elasticsearch/src'
Makefile:421: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/dovecot-elastic/fts-elasticsearch'
Makefile:352: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by atkinsj** [comment]
Cleaning up old issues. Let me know if you're still experiencing issues.
