### ISSUE TITLE
dovecot-config not found

### ISSUE THREAD

**Issue by mohiddinster** [ascendantcom/fts-elasticsearch#12]
Im trying to install in my ubuntu server 16.04. I have provided dovecot path still it says not found, whats wrong here?

root@server:/tmp/fts-elasticsearch# ./configure --with-dovecot=/etc/dovecot
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '0' is supported by ustar format... yes
checking whether GID '0' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
checking whether to enable maintainer-specific portions of Makefiles... no
checking for dovecot-config in "/etc/dovecot"... not found
configure: 
configure: Use --with-dovecot=DIR to provide the path to the dovecot-config file.
configure: error: dovecot-config not found

**Comment by timgws** [comment]
Crazy question, but do you have the package `dovecot-dev` installed? Double check that you do, and try running `./configure` again (without `--with-dovecot`).

**Comment by archont00** [comment]
@mohiddinster : having dovecot sources is not enough, you need to compile them (configure && make) so that the file dovecot-config gets created.

**Comment by tilllt** [comment]
On a debian system it would probably be useful to use "apt-build install dovecot" to install dovecot from source. The sources afterwards reside in: /var/cache/apt-build/build/dovecot-x.x.yy ... 

There is no dovecot-config though after the process, but only a dovecot-config.in.in ... can i convince the ./configure to use this instead?

**Comment by atkinsj** [comment]
Cleaning up old issues. Please re-open if you're still experiencing this issue.
