### ISSUE TITLE
mapper_parsing_exception, failed to parse caused_by json_parse_exception: Duplicate field 'received'

### ISSUE THREAD

**Issue by infernix** [ascendantcom/fts-elasticsearch#17]
Seems that in ES 2.4(?) and up, duplicate fields are not accepted any longer. And obviously mails usually have multiple `Received` headers.

Not sure how to deal with this, still investigating.

**Comment by infernix** [comment]
FWIW this applies to all sorts of fields; some parsing shows it happening for `x-received` as well. I guess a quick hack is in order to just add these one time to the json output for `_bulk`

**Comment by infernix** [comment]
Well, this seems pretty relevant today: https://github.com/elastic/elasticsearch/commit/dbb6fe58faf27598d7bb735365710903c1ef137d

It looks like with ES v5 and v6 you can set `-Des.xcontent.strict_duplicate_detection=false` but that's going away in 7.

**Comment by infernix** [comment]
Confirmed that adding that flag fixes the error logging for ES 6.4. Will send PR with documentation update.

**Comment by atkinsj** [comment]
#16 merged.
