### ISSUE TITLE
indexing attachments

### ISSUE THREAD

**Issue by JulienCharge** [ascendantcom/fts-elasticsearch#2]
Hello,
I am trying to set up your plugins.
I have a question concerning the attachments.

Is it possible to index the room joined in ElasticSearch , because I do not see the attachment fields?

thank you

Awaiting your reply

Best Regards,
Julian

**Comment by atkinsj** [comment]
Hi Julian,

No support for attachments yet. I'm not sure how to approach this; Dovecot added support for this in 2.1 and it is documented at http://wiki2.dovecot.org/Plugins/FTS (see "Indexing Attachments").

In theory with Dovecot configured correctly then fts-elasticsearch should index any field that Dovecot provides it and it should work seamlessly but I haven't had a chance to confirm this.

I'll try and get around to configuring a suitably sized Dovecot instance this weekend and running it up for you.

Josh

**Comment by JulienCharge** [comment]
thank you ,

I have a small quesrion is it possible in a simple way to add fields in the json . This field specifies the name of dovecot directory (eg .INBOX.archives ) ?

Because we would like to search ElasticSearch based on subdirectory of the box.

According to you is that this manipulation is possible?

Thank you for your answers and your time.

Best Regards,
Julian

**Comment by atkinsj** [comment]
No probs.

I'm sorry I'm not sure what you mean. fts-elasticsearch indexes every field
Dovecot provides it so if Dovecot makes this field available for indexing,
we would index it. All subdirectories of mailboxes should be indexed too,
though, as they each get their own GUID.

Do you have an example?

Cheers,
Josh

On 30 January 2015 at 01:47, JulienCharge notifications@github.com wrote:

> thank you ,
> 
> I have a small quesrion is it possible in a simple way to add fields in
> the json . This field specifies the name of dovecot directory (eg
> .INBOX.archives ) ?
> 
> Because we would like to search ElasticSearch based on subdirectory of the
> box.
> 
> According to you is that this manipulation is possible?
> 
> Thank you for your answers and your time.
> 
> Best Regards,
> Julian
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ascendantcom/fts-elasticsearch/issues/2#issuecomment-72036277
> .

##

**Comment by JulienCharge** [comment]
Hello,
BY example we would have a field more with the place or stored mail .

For example I receives an email in my box , dovecot is indexed in ElasticSearch .

I chose to move to the directory in my inbox "Archive" .

Here is the json that we would like indexes:

{
    "uid" : 3,
    "box" :" f40efa2f8f44ad54424000006e8130ae "
    " repo ": " INBOX.Archive "
    "Return- Path" : "< josh@localhost.localdomain > "
    "X -Original -To" : "josh "
    " Delivered-To ": " josh@localhost.localdomain "
    "Received ": " by localhost.localdomain ( Postfix , from userid 1000) id 07DA3140314 ; Thu, January 8, 2015 0:20:05 +1100 ( AEDT ) "
    "Date ": " Thu, January 8, 2015 0:20:05 +1100 "
    "To" , " josh@localhost.localdomain "
    "Subject" , " Test # 3 "
    " User-Agent ": " Heirloom mailx 12.5 7 \ / 5 \ / 10 "
    " MIME-Version ": " 1.0 "
    "Content- Type" , " text \ / plain; charset = us-ascii "
    "Content- Transfer-Encoding ": " 7bit "
    "Message- Id ": " < 20150107132005.07DA3140314@localhost.localdomain > "
    "From" : "josh < josh@localhost.localdomain > "
    "body ": " This is the body of Test # 3 . \ n"
}

**Comment by extremeshok** [comment]
This will be of use, https://wiki.apache.org/tika/TikaJAXRS

Tika is about the best way to extract metadata and text from attachments.

you should be able to send the attachments to the tika server and then the results to elasticsearch

**Comment by geekpete** [comment]
A recent blog post on the future of attachment processing with Elasticsearch can be found here: https://www.elastic.co/blog/the-future-of-attachments-for-elasticsearch-and-dotnet

(It does contain some dotnet specific examples/details, but the overall info on attachment processing is still relevant.)

**Comment by atkinsj** [comment]
Happy to take a PR for this but no time to work on it as of right now.
