### ISSUE TITLE
Compiling on ARM

### ISSUE THREAD

**Issue by lourou** [ascendantcom/fts-elasticsearch#3]
Hi,

Really interested in your Dovecot search with Elastic!

I am trying to build it on ARMv7 along with dovecot-2.2.18 source code.

`./configure --with-dovecot=../dovecot-2.2.18`

The configure command above returns the following and I am not sure what does the "dovecot-config" file refers to.

`checking for dovecot-config in "/root/dovecot/dovecot-2.2.18"... not found`
`configure: Use --with-dovecot=DIR to provide the path to the dovecot-config file.`
`configure: error: dovecot-config not found`

Thanks a lot for your help,
Louis

**Comment by timgws** [comment]
Have you completed dovecot from source before starting the fts compile?
Have you installed dovecot?

---- On Sun, 13 Sep 2015 05:36:04 +1000 notifications@github.com wrote ---- Hi,
Really interested in your Dovecot search with Elastic!
I am trying to build it on ARMv7 along with dovecot-2.2.18 source code.
./configure --with-dovecot=../dovecot-2.2.18
The configure command above returns the following and I am not sure what does the "dovecot-config" file refers to.
checking for dovecot-config in "/root/dovecot/dovecot-2.2.18"... not found

configure: Use --with-dovecot=DIR to provide the path to the dovecot-config file.

configure: error: dovecot-config not found
Thanks a lot for your help,

Louis

**Comment by lourou** [comment]
I had a 2.1 Installed. Just compiled 2.2.18 and managed to ./configure fts-elasticsearch, thanks!

The make did not go through though:

`In file included from fts-elasticsearch-plugin.c:8:0:`
`fts-elasticsearch-plugin.h:5:29: fatal error: fts-api-private.h: No such file or directory`

Strange thing is this file is found:
`../dovecot-2.2.18/src/lib/module-context.h`

but this one is not:
`../dovecot-2.2.18/src/plugins/fts/fts-api-private.h`

Any clue?
Thanks

**Comment by atkinsj** [comment]
Can you confirm the -I path's on the gcc calls? The first one should be:

`libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I/tmp/dovecot/dovecot-2.2.18//src/plugins/fts`

fts-api-private.h exists in src/plugins/fts for Dovecot.

**Comment by lourou** [comment]
Yes, here are the first calls:

`libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../dovecot-2.2.18/src/plugins/fts -I/root/dovecot/dovecot-2.2.18 -I/root/dovecot/dovecot-2.2.18/src/lib (...)`

The file ../dovecot-2.2.18/src/plugins/fts/fts-api-private.h exists in the dovecot source directory.

**Comment by atkinsj** [comment]
Interesting--that's definitely a bug. Can you do a make clean and then re-run configure with the full path to dovecot-2.2.18?

`./configure --with-dovecot=/root/dovecot/dovecot-2.2.18`

I'll push a fix for this tomorrow.

**Comment by lourou** [comment]
make clean and full absolute path made it :+1: Thanks!

**Comment by straight-shoota** [comment]
**ping @atkinsj** bug ist still unresolved... but using full path works for me too.

**Comment by atkinsj** [comment]
Sorry for that! A fix is up now.
