### ISSUE TITLE
Various centos 6 build warnings

### ISSUE THREAD

**Issue by extremeshok** [ascendantcom/fts-elasticsearch#5]
centos 6 with epel repo

The make and make install does complete without issues and the plugin does work.

libtoolize being run by autoreconf is not creating ltmain.sh in the auxillary directory

```
[root@fts-elasticsearch]# ./autogen.sh
Preparing the fts-elasticsearch build system...please wait

Found GNU Autoconf version 2.63
Found GNU Automake version 1.11.1
Found GNU Libtool version 2.2.6b

Automatically preparing build ... Warning: autoreconf failed
libtoolize being run by autoreconf is not creating ltmain.sh in the auxillary directory like it should
Attempting to run the preparation steps individually

Preparing build ...
Warning: autoconf seems to have succeeded by removing the following options:
        AUTOCONF_OPTIONS="-f"

Removing those options should not be necessary and indicate some other
problem with the build system.  The build preparation is highly suspect
and may result in configuration or compilation errors.  Consider
rerunning the build preparation with verbose output enabled.
        ./autogen.sh --verbose

Continuing build preparation ... done

The fts-elasticsearch build system is now prepared.  To build here, run:
  ./configure
  make
```

**Comment by extremeshok** [comment]
AC_CHECK_HEADER_STDBOOL: command not found

```
[root@fts-elasticsearch]# ./configure --prefix=/usr --with-dovecot=/usr/lib64/dovecot/
...
checking syslog.h presence... yes
checking for syslog.h... yes
checking for unistd.h... (cached) yes
./configure: line 13685: AC_CHECK_HEADER_STDBOOL: command not found
checking for size_t... yes
checking for uint32_t... yes
checking for memset... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating dummy-config.h
config.status: dummy-config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands

Install prefix       : /usr
Lib install prefix   : /usr/lib64/dovecot

```

**Comment by extremeshok** [comment]
Is lib21_fts_elasticsearch_plugin.a and lib21_fts_elasticsearch_plugin.la meant to be copied to the /usr/lib64/dovecot/ directory when running make install ?

```
[root@fts-elasticsearch]# ls -l  /usr/lib64/dovecot/lib21_fts_elasticsearch*
-rw-r--r-- 1 root root 201808 Dec 16 13:32 /usr/lib64/dovecot/lib21_fts_elasticsearch_plugin.a
-rwxr-xr-x 1 root root   1088 Dec 16 13:32 /usr/lib64/dovecot/lib21_fts_elasticsearch_plugin.la
-rwxr-xr-x 1 root root 129674 Dec 16 13:32 /usr/lib64/dovecot/lib21_fts_elasticsearch_plugin.so
```

**Comment by atkinsj** [comment]
Can you run the ./autogen.sh with the --verbose as suggested if you get a chance? I'll spin up a CentOS6 box and take a look.

I've pushed a fix removing AC_CHECK_HEADER_STDBOOL because we don't require stdbool anymore.

**Comment by atkinsj** [comment]
I don't get the same behaviour under CentOS6.7 running the same autoconf/automake/libtool versions as you; do you want to try grabbing it again and giving it another shot? I did recently clean-up some old autoconf artefacts that were left in the source control that may have caused this.

**Comment by extremeshok** [comment]
confirmed, all working now.

Is lib21_fts_elasticsearch_plugin.a and lib21_fts_elasticsearch_plugin.la meant to be copied to the /usr/lib64/dovecot/ directory when running make install ?

[root@fts-elasticsearch]# ls -l  /usr/lib64/dovecot/lib21_fts_elasticsearch*
-rw-r--r-- 1 root root 201808 Dec 16 13:32 /usr/lib64/dovecot/lib21_fts_elasticsearch_plugin.a
-rwxr-xr-x 1 root root   1088 Dec 16 13:32 /usr/lib64/dovecot/lib21_fts_elasticsearch_plugin.la
-rwxr-xr-x 1 root root 129674 Dec 16 13:32 /usr/lib64/dovecot/lib21_fts_elasticsearch_plugin.so

**Comment by atkinsj** [comment]
Awesome.

Yep -- the .la is in lieu of a package config and the .a is there in case some crazy person wants a static version. It's in line with the rest of the dovecot plugins.
